"""Baseline schema creation for new deployments

Revision ID: a46528f216f8
Revises: d7ac3602a5e8
Create Date: 2025-10-21 16:45:12.765660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46528f216f8'
down_revision: Union[str, Sequence[str], None] = 'd7ac3602a5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration documents the baseline schema for new deployments
    # For existing databases, schema already exists - this is a no-op
    # For new databases, tables should be created via db_setup/create_database.py
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration documents existing schema, downgrade is not supported
    # as it would destroy existing data
    raise Exception("Cannot downgrade - this migration documents existing schema")
    # ### end Alembic commands ###
