"""Complete schema migration with all tables

Revision ID: d7ac3602a5e8
Revises: 20d186398248
Create Date: 2025-10-21 16:44:17.525197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ac3602a5e8'
down_revision: Union[str, Sequence[str], None] = '20d186398248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration documents the complete existing schema
    # Tables were created manually, so upgrade is a no-op
    # This migration serves as documentation of current schema state
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration documents existing schema, downgrade is not supported
    # as it would destroy existing data
    raise Exception("Cannot downgrade - this migration documents existing schema")
    # ### end Alembic commands ###
